telegram:
  token: 5183245973:AAHaGdOmX9OkwDLvzEhMMW3NhXrN9t67ghw # Telegram bot tokens look like this: 113031530:AAH_4c5Gt9gsVu82OVNjUV7poU7PodYiNsA
  useFirstNameInsteadOfUsername: true
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
discord:
  useNickname: false
  token: MTAxNTI0MzE5NTMyOTgxNDYxOQ.GBtwe8.gsuDt7ldDOFucYrlPpOFRcmxZPRGgxhzdL5Q4Q # Discord bot tokens look like this: MjI3MDA1NzIvOBQ2MzAzMiMz.DRf-aw.N0MVYtDxXYPSQew4g2TPqvQve2c
  skipOldMessages: true
  replyLength: 100
  maxReplyLines: 2
bridges:
  - name: NSFW bridge
    direction: both
    telegram:
      chatId: -1001428895053 # Remember that Telegram group and channel IDs are negative. Include the `-` if you are bridging a group or a channel
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      relayCommands: false
      crossDeleteOnDiscord: true
    discord:
      channelId: '937573658870829086' # This ID must be wrapped in single quotes. Example: '244791815503347712'
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnTelegram: true
  - name: Channel bridge
    direction: both
    telegram:
      chatId: -1001579792372 # Remember that Telegram group and channel IDs are negative. Include the `-` if you are bridging a group or a channel
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      relayCommands: false
      crossDeleteOnDiscord: true
    discord:
      channelId: '1053330422441988166' # This ID must be wrapped in single quotes. Example: '244791815503347712'
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnTelegram: true
  - name: Default bridge
    direction: both
    telegram:
      chatId: -1001793349770 # Remember that Telegram group and channel IDs are negative. Include the `-` if you are bridging a group or a channel
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      relayCommands: false
      crossDeleteOnDiscord: true
    discord:
      channelId: '937590109174382603' # This ID must be wrapped in single quotes. Example: '244791815503347712'
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnTelegram: true
debug: false
messageTimeoutAmount: 24
messageTimeoutUnit: 'hours' # This string must be a valid Moment time format. Example: seconds, minutes, hours, days, weeks, months, years
persistentMessageMap: false
